version: "3.9"
   
services:
  db:
    image: nouchka/sqlite3
    environment:
      - SQLITE3_DB=sqlite3
      - SQLITE3_USER=sqlite3
      - SQLITE_PASSWORD=sqlite3
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db

